# Generated by Django 5.0.4 on 2024-04-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="points_to_give",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="student",
            name="points",
            field=models.FloatField(default=0.0),
        ),
    ]
