# Generated by Django 5.0.4 on 2024-04-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_server_points_to_give_student_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="last_participation",
            field=models.DateTimeField(null=True),
        ),
    ]
